version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15.1-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=django_dev
  web:
    container_name: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      -8000:8000
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db


volumes:
  postgres_data: