version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15.1-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuserprod
      - POSTGRES_PASSWORD=prodpass
      - POSTGRES_DB=django_prod
  web:
    container_name: web
    build: .
    volumes:
      - ./:/app
      - static_files:/app/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_files:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
